version: '3'

services:
  my-running-app:
    container_name: my-running-app
    restart: always
    image: my-apache2
    privileged: true
    sysctls:
      net.core.somaxconn: '511'   
    volumes:
    - $PWD/public-html:/usr/local/apache2/htdocs
    ports:
    - "8080:80"
    environment:    
    - TZ=Asia/Taipei
 